spring:
  jmx:
    default-domain:
     localhost

spring:
  application:
    name: turbine

turbine:
  appConfig: east-1

spring:
  cloud:
    consul:
      host: consul
      port: 8500

server:
  port: 8990

